### ISSUE TITLE
My server can't load this plugin.

### ISSUE THREAD

**Issue by zsn741656478** [AuraDevelopmentTeam/AuraSunDial#1]
My server version: spongevanilla-1.12.2-7.1.0-BETA-39.jar
Error report: http://paste.ubuntu.org.cn/4320378

**Comment by BrainStone** [comment]
That’s because it is a bungeecord plugin.

**Comment by BrainStone** [comment]
I’m blind. My bad. I’ll have a look later. Shouldn’t take care of GitHub issues when I’m half asleep.

**Comment by BrainStone** [comment]
There must be more to this error, looks like it's cut off.

**Comment by zsn741656478** [comment]
OK. This all
http://paste.ubuntu.org.cn/4321157

**Comment by zsn741656478** [comment]
Can you help me?

**Comment by BrainStone** [comment]
I’m trying to reproduce this bug. I’m just pretty busy and don’t have much time. So I’m not sure how long it’ll take.

**Comment by BrainStone** [comment]
Ok. Try the new upload on Ore. I noticed I uploaded the wrong file back then. :/

Thanks for pointing this out.
